name = "OPTinv"
uuid = "be359dbc-e715-4152-92a8-ea345ee2ca4a"
authors = ["B. Hamilton"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
